language: ruby
addons:
  postgresql: 9.6
services:
  - postgresql 
rvm:
  - 2.4.4
  - 2.5.1
before_install: gem install bundler -v 1.11.2
script:
  - bundle exec rake db:create
  - bundle exec rake spec
