language: ruby
dist: xenial
matrix:
  include:
    - name: "Run Ruby 2.4.4 against pg 9"
      rvm: 2.4.4
      addons:
        postgresql: 9.6
      gemfile:
      - gemfiles/activerecord_5.1.gemfile
      - gemfiles/activerecord_5.2.gemfile
    - name: "Run Ruby 2.4.4 against pg 10"
      rvm: 2.4.4
      addons:
        postgresql: 10
      gemfile:
      - gemfiles/activerecord_5.1.gemfile
      - gemfiles/activerecord_5.2.gemfile
    - name: "Run Ruby 2.5.1 against pg 9"
      rvm: 2.5.1
      addons:
        postgresql: 9.6
      gemfile:
      - gemfiles/activerecord_5.1.gemfile
      - gemfiles/activerecord_5.2.gemfile
    - name: "Run Ruby 2.5.1 against pg 10"
      rvm: 2.5.1
      addons:
        postgresql: 10
      gemfile:
      - gemfiles/activerecord_5.1.gemfile
      - gemfiles/activerecord_5.2.gemfile
before_install: gem install bundler -v 1.11.2
script:
  - bundle exec rake db:create
  - bundle exec rake spec
